In [1]:
import dcbench

In [2]:
dcbench.tasks

,name,summary
minidata,Minimal Data Selection,"Given a large training dataset, what is the sm..."
slice_discovery,Slice Discovery,Machine learnings models that achieve high ove...
budgetclean,Data Cleaning on a Budget,"When it comes to data preparation, data cleani..."

In [3]:
slice_problem_df = dcbench.tasks["slice_discovery"].problems.df

slice_problem_df

,alpha,dataset,n_pred_slices,slice_category,slice_names,target_name
p_72776,0.2000,celeba,5,correlation,"[wearing_lipstick=0_young=1, wearing_lipstick=...",wearing_lipstick
p_72793,0.6000,celeba,5,correlation,"[wearing_necklace=0_black_hair=1, wearing_neck...",wearing_necklace
p_72800,0.2000,celeba,5,correlation,"[wearing_necklace=0_brown_hair=1, wearing_neck...",wearing_necklace
p_72799,0.6000,celeba,5,correlation,"[wearing_necklace=0_smiling=1, wearing_necklac...",wearing_necklace
p_72802,0.2000,celeba,5,correlation,"[wearing_necklace=0_wearing_lipstick=1, wearin...",wearing_necklace
...,...,...,...,...,...,...
p_122649,0.2000,imagenet,5,noisy_label,[watch.n.01],timepiece.n.01
p_117333,0.0500,imagenet,5,rare,[cart.n.01],vehicle.n.01
p_118951,0.0500,imagenet,5,rare,[punch.n.02],food.n.01
p_120032,0.0500,imagenet,5,rare,[mushroom.n.05],vegetable.n.01
p_118660,0.0171,imagenet,5,rare,[menu.n.02],food.n.01

In [4]:
celeb_a_df = slice_problem_df.loc[slice_problem_df['dataset'] == 'celeba']

In [5]:
celeb_a_df['slice_category'].value_counts()

correlation    520
Name: slice_category, dtype: int64

In [6]:
import numpy as np

In [7]:
slices = np.array(celeb_a_df['slice_names'])

In [8]:
celeb_a_df

,alpha,dataset,n_pred_slices,slice_category,slice_names,target_name
p_72776,0.2,celeba,5,correlation,"[wearing_lipstick=0_young=1, wearing_lipstick=...",wearing_lipstick
p_72793,0.6,celeba,5,correlation,"[wearing_necklace=0_black_hair=1, wearing_neck...",wearing_necklace
p_72800,0.2,celeba,5,correlation,"[wearing_necklace=0_brown_hair=1, wearing_neck...",wearing_necklace
p_72799,0.6,celeba,5,correlation,"[wearing_necklace=0_smiling=1, wearing_necklac...",wearing_necklace
p_72802,0.2,celeba,5,correlation,"[wearing_necklace=0_wearing_lipstick=1, wearin...",wearing_necklace
...,...,...,...,...,...,...
p_72357,0.4,celeba,5,correlation,"[eyeglasses=0_black_hair=1, eyeglasses=1_black...",eyeglasses
p_72348,0.8,celeba,5,correlation,"[eyeglasses=0_gray_hair=1, eyeglasses=1_gray_h...",eyeglasses
p_72362,0.4,celeba,5,correlation,"[eyeglasses=0_mustache=1, eyeglasses=1_mustach...",eyeglasses
p_72367,0.8,celeba,5,correlation,"[eyeglasses=0_no_beard=1, eyeglasses=1_no_bear...",eyeglasses
p_72386,0.4,celeba,5,correlation,"[eyeglasses=0_wearing_hat=1, eyeglasses=1_wear...",eyeglasses

In [9]:
for s in slices[:10]:
    print(s)

['wearing_lipstick=0_young=1', 'wearing_lipstick=1_young=0']
['wearing_necklace=0_black_hair=1', 'wearing_necklace=1_black_hair=0']
['wearing_necklace=0_brown_hair=1', 'wearing_necklace=1_brown_hair=0']
['wearing_necklace=0_smiling=1', 'wearing_necklace=1_smiling=0']
['wearing_necklace=0_wearing_lipstick=1', 'wearing_necklace=1_wearing_lipstick=0']
['wearing_necklace=0_young=1', 'wearing_necklace=1_young=0']
['wearing_necktie=0_black_hair=1', 'wearing_necktie=1_black_hair=0']
['wearing_necktie=0_eyeglasses=1', 'wearing_necktie=1_eyeglasses=0']
['wearing_necktie=0_mustache=1', 'wearing_necktie=1_mustache=0']
['wearing_necktie=0_no_beard=1', 'wearing_necktie=1_no_beard=0']

In [10]:
slice_problem_df.loc[slice_problem_df['dataset'] == 'imagenet']

,alpha,dataset,n_pred_slices,slice_category,slice_names,target_name
p_122446,0.3000,imagenet,5,noisy_label,[cougar.n.01],cat.n.01
p_122493,0.3000,imagenet,5,noisy_label,"[leopard.n.02, tiger.n.02, lion.n.01]",big_cat.n.01
p_122484,0.3000,imagenet,5,noisy_label,"[clock.n.01, watch.n.01, clock.n.01]",timepiece.n.01
p_121702,0.3000,imagenet,5,noisy_label,"[sauce.n.01, concoction.n.01]",food.n.01
p_121703,0.3000,imagenet,5,noisy_label,"[cornet.n.01, organ.n.05, chime.n.01]",musical_instrument.n.01
...,...,...,...,...,...,...
p_122649,0.2000,imagenet,5,noisy_label,[watch.n.01],timepiece.n.01
p_117333,0.0500,imagenet,5,rare,[cart.n.01],vehicle.n.01
p_118951,0.0500,imagenet,5,rare,[punch.n.02],food.n.01
p_120032,0.0500,imagenet,5,rare,[mushroom.n.05],vegetable.n.01
p_118660,0.0171,imagenet,5,rare,[menu.n.02],food.n.01

In [23]:
def get_problem_by_id(pid):
    return dcbench.tasks["slice_discovery"].problems[pid]

In [24]:
# get one of the problems

In [31]:
problem = get_problem_by_id("p_121703")

In [33]:
problem

SliceDiscoveryProblem(artifacts={'activations': 'DataPanelArtifact', 'base_dataset': 'VisionDatasetArtifact', 'clip': 'DataPanelArtifact', 'model': 'ModelArtifact', 'test_predictions': 'DataPanelArtifact', 'test_slices': 'DataPanelArtifact', 'val_predictions': 'DataPanelArtifact'}, attributes={'alpha': 0.30000000000000004, 'dataset': 'imagenet', 'n_pred_slices': 5, 'slice_category': 'noisy_label', 'slice_names': ['cornet.n.01', 'organ.n.05', 'chime.n.01'], 'target_name': 'musical_instrument.n.01'})

In [32]:
problem['activations']

DataPanel(nrows: 8973, ncols: 2)

In [28]:
problem = get_problem_by_id("p_122493")

In [30]:
problem['activations']

DataPanel(nrows: 8923, ncols: 2)

In [15]:
problem.artifacts["test_predictions"].download()

False

In [16]:
problem.artifacts["test_predictions"].load()

/Users/narij/opt/anaconda3/lib/python3.8/site-packages/meerkat/ml/__init__.py:7: ExperimentalWarning: The `meerkat.ml` module is experimental and has limited test coverage. Proceed with caution.
  warnings.warn(

DataPanel(nrows: 6004, ncols: 4)

In [ ]:
problem.artifacts["base_dataset"].download()

Each problem is made up of a set of artifacts: a dataset with features to clean, a dataset and a model to perform error analysis on. In dcbench , these artifacts are represented by instances of dcbench.Artifact. We can think of each Problem object as a container for Artifact objects.

Note that Artifact objects donâ€™t actually hold their underlying data in memory. Instead, they hold pointers to where the Artifact lives in dcbench cloud storage and, if itâ€™s been downloaded, where it lives locally on disk. This makes the Problem objects very lightweight.

* Their 'download' method and tutorial are both unfinished, https://github.com/data-centric-ai/dcbench/blob/main/dcbench/common/artifact.py 


* https://github.com/data-centric-ai/dcbench/blob/main/dcbench/common/artifact.py

In [ ]:
problem.artifacts["model"].download()

In [ ]:
torch_model = problem.artifacts["model"].load()

In [ ]:
torch_model

* https://dcbench.readthedocs.io/en/latest/_modules/dcbench/common/table.html#Table

In [ ]:
slice_problem_df['dataset'].value_counts()

In [ ]:
## what are these slices?

imagenet_problem_df =

In [ ]:
problem_id = ''